sudo: false
dist: precise

addons:
  apt:
    packages:
      graphviz
      optipng
      libjpeg-progs
      plantuml

branches:
  only:
  - master
language: python
python:
- 3.6
before_install:
- wget "http://sourceforge.net/projects/plantuml/files/plantuml.jar/download"
- export PATH=$PATH:$PWD
- git submodule update --init --recursive
install: ./setup.sh

script: make html
notifications:
  email:
    on_success: always
    on_failure: always

