branches:
  only:
  - master
language: python
python:
- 3.6
before_install:
- git submodule update --init --recursive
install:
- 
- ./setup.sh

script:
notifications:
  email:
    on_success: always
    on_failure: always

